# Generated by Django 5.2.17 on 2026-09-17 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0011_quoterequest_assigned_businesses'),
    ]

    operations = [
        migrations.AddField(
            model_name='directoffer',
            name='confirmed_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='גובה מאושר במטרים'),
        ),
        migrations.AddField(
            model_name='directoffer',
            name='confirmed_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='אורך מאושר במטרים'),
        ),
        migrations.AddField(
            model_name='directoffer',
            name='confirmed_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='רוחב מאושר במטרים'),
        ),
        migrations.AddField(
            model_name='directoffer',
            name='visualization',
            field=models.FileField(blank=True, upload_to='visualizations/%Y/%m/', verbose_name='הדמיה ללקוח'),
        ),
        migrations.AddField(
            model_name='generaloffer',
            name='confirmed_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='גובה מאושר במטרים'),
        ),
        migrations.AddField(
            model_name='generaloffer',
            name='confirmed_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='אורך מאושר במטרים'),
        ),
        migrations.AddField(
            model_name='generaloffer',
            name='confirmed_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='רוחב מאושר במטרים'),
        ),
        migrations.AddField(
            model_name='generaloffer',
            name='visualization',
            field=models.FileField(blank=True, upload_to='visualizations/%Y/%m/', verbose_name='הדמיה ללקוח'),
        ),
        migrations.AddField(
            model_name='generalrequest',
            name='estimated_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='גובה משוער במטרים'),
        ),
        migrations.AddField(
            model_name='generalrequest',
            name='estimated_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='אורך משוער במטרים'),
        ),
        migrations.AddField(
            model_name='generalrequest',
            name='estimated_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='רוחב משוער במטרים'),
        ),
        migrations.AddField(
            model_name='generalrequest',
            name='measurement_confidence',
            field=models.CharField(default='הערכה ראשונית', max_length=50, verbose_name='רמת ביטחון'),
        ),
        migrations.AddField(
            model_name='generalrequest',
            name='measurement_method',
            field=models.CharField(blank=True, max_length=50, verbose_name='שיטת מדידה'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='estimated_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='גובה משוער במטרים'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='estimated_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='אורך משוער במטרים'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='estimated_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='רוחב משוער במטרים'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='measurement_confidence',
            field=models.CharField(default='הערכה ראשונית', max_length=50, verbose_name='רמת ביטחון'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='measurement_method',
            field=models.CharField(blank=True, max_length=50, verbose_name='שיטת מדידה'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_text',
            field=models.CharField(default='OrProServices .אתר דמו', max_length=180, verbose_name='טקסט תחתון'),
        ),
        migrations.CreateModel(
            name='MeasurementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='measurements/%Y/%m/', verbose_name='תמונת מדידה')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('general_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurement_images', to='planner.generalrequest')),
                ('service_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurement_images', to='planner.servicerequest')),
            ],
            options={
                'verbose_name': 'תמונת מדידה',
                'verbose_name_plural': 'תמונות מדידה',
            },
        ),
    ]
