# Generated by Django 5.2.17 on 2026-09-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0012_measurement_intake_and_visualization'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrequestlink',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='שם הלקוח'),
        ),
        migrations.AddField(
            model_name='generalrequest',
            name='submission_id',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='measurementimage',
            name='caption',
            field=models.CharField(blank=True, max_length=140, verbose_name='תיאור הצילום'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='submission_id',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
